version: '3'
services:
  storage:
    build:
      context: ./storage
    volumes:
      - ./storage/app/storage_log.txt:/app/storage_log.txt
    ports:
      - "5050:5050"
  service2:
    build:
      context: ./service2
    volumes:
      - ./vstorage:/vstorage
    ports:
      - "3000:3000"
  service1:
    build:
      context: ./service1
    ports:
      - "8199:8199"
    volumes:
      - ./vstorage:/vstorage
networks:
  default:
    driver: bridge