
services:
  storage:
    build:
      context: ./storage
    volumes:
      - ./storage/app/storage_log.txt:/app/storage_log.txt
  service2:
    build:
      context: ./service2
    volumes:
      - ./vstorage:/vstorage
  service1:
    build:
      context: ./service1
    ports:
      - "8199:8199"
    volumes:
      - ./vstorage:/vstorage
networks:
  default:
    driver: bridge